# Main application configuration
service: asantiya
image: ${HOST_USER}/asantiya
# Server connection details (use environment variables)
server: ${SERVER}
# Port mappings (host:container)
app_ports: 8020:8020
# Host machine configuration (set to false if not needed)
host: false
# Build configuration
builder:
  # Build machine specifications
  arch: amd64
  remote: ssh://build@ci.example.com
# Container services definitions
accessories:
  db:
    # postgres service
    service: asantiya-db
    image: postgres:13
    ports: 8069:8069
    options:
      restart: always
    env:
      POSTGRES_PASSWORD: some-strong-password-for-postgressql
    volumes:
    - myvolume:/var/lib/postgresql/data
    network: asantiya
