name: Build and Deploy to Server

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nextra-app .

      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: nextra-docker-image
          path: /tmp/nextra-app.tar
          retention-days: 1

      - name: Deploy to Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          # Install SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Copy and load Docker image
          scp -o StrictHostKeyChecking=no /tmp/nextra-app.tar $SSH_USER@$SERVER_IP:/tmp/nextra-app.tar
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "
            docker load -i /tmp/nextra-app.tar && \
            docker stop nextra-app || true && \
            docker rm nextra-app || true && \
            docker run -d --name nextra-app -p 3006:3000 --restart unless-stopped nextra-app
          "